### ISSUE TITLE
Slide trace baseline vertically

### ISSUE THREAD

**Issue by michaelpeshkin** [nLabs-nScope/nScope#31] opened 2023-09-27 21:19 UTC
Want to be able to adjust trace baseline offset on the scope face, rather than needing to find the slider inside the CH1 box.  (It isn't there at present, as far as I can tell)    Trigger level wants to be this way too: with the trigger threshold dotted line the same color as the trigger channel.

1.0.0 beta 2

**Comment by davidjmeyer** [comment] 2023-10-06 03:19
This looks like a duplicate of #26. We'll track this there.

**Closed by davidjmeyer** 2023-10-06 03:19 UTC
