### ISSUE TITLE
occasional stuck sweep

### ISSUE THREAD

**Issue by michaelpeshkin** [nLabs-nScope/nScope#41] opened 2023-10-25 15:52 UTC
https://photos.app.goo.gl/pcQzw3KzZiebzVjB9

Encountered this in class and videoed it.  Sweep didn't restart despite flipping trigger on/off or toggling run/stop.  It did restart when I changed the time base.

**Comment by davidjmeyer** [comment] 2024-07-24 04:09
I think this is a duplicate of #77

**Closed by davidjmeyer** 2024-07-24 04:09 UTC
Labels: duplicate
