### ISSUE TITLE
File writing

### ISSUE THREAD

**Issue by michaelpeshkin** [nLabs-nScope/nScope#46] opened 2023-10-26 12:29 UTC
File writing CSV, PNG, JPG.   I like that you are keeping the face as clean as possible.  I’d prefer these as a menu item with a keystroke attached.  And my preference is that it doesn’t ask you any questions, just instantly writes a time-stamped file.   (Like command-option-3; do you want to discuss what to name your screencapture, or do you just want to capture it and get back to work?)   You want this to be easy to do multiple times.

**Comment by davidjmeyer** [comment] 2023-11-08 04:41
Duplicate of #27

**Closed by davidjmeyer** 2023-11-08 04:41 UTC
